### ISSUE TITLE
It's the length of the entry

### ISSUE THREAD

**Issue by solarmist** [fab-jul/parse_dictionaries#1]
https://github.com/fab-jul/parse_dictionaries/blob/115157ff7d028f5d5523e9399bb06d17a5033511/reverse_data.py#L284

Decode it using 

    length = int.from_bytes(input_bytes[:4], byteorder="little")
    entry = input_bytes[4:][:length].decode('utf8')

**Comment by solarmist** [comment]
Nm, I've created a general tool for extracting the XML. 
https://github.com/solarmist/apple-peeler

**Comment by fab-jul** [comment]
Looks very cool!
