### ISSUE TITLE
not working on the latest Mac Os Monterey

### ISSUE THREAD

**Issue by pk49800** [fab-jul/parse_dictionaries#3]
➜  Downloads python reverse_data.py --lookup handle --output_path lookup/lookup.html
Parsing /System/Library/AssetsV2/com_apple_MobileAsset_DictionaryServices_dictionaryOSX/691342e919a43780131154ea889de5d61bc35267.asset/AssetData/Oxford Dictionary of English.dictionary/Contents/Resources/Body.data...
Splitting...
index
bytes
as chars
--------------------------------------------------
       895 b'O\x06\x00\x00'               007
      2509 b'\xf8\x02\x00\x00'            2.0
      3268 b'\xa3\t\x00\x00'              404
      5734 b'\x8b\x04\x00\x00'            420
      6896 b'#\x08\x00\x00'               4D printing
      8978 b'\x8a\x06\x00\x00'            4K
     10651 b'\x9a\x02\x00\x00'            5G
     11316 b'\x9d\x02\x00\x00'            911
     11984 b'D\x18\x00\x00'               999
     18195 b'\xc3\x0c\x00\x00'            a
     21461 b'{"\x00\x00'                  a
     30287 b'\xc1\x11\x00\x00'            A
     34831 b'Z\x06\x00\x00'               A
     36456 b'f\x0b\x00\x00'               a-
     39373 b'\x91\x04\x00\x00'            a-
     40541 b'\x12\x08\x00\x00'            a-
     42606 b'\xeb\x0c\x00\x00'            a-
     45912 b'K\x06\x00\x00'               -a
     47522 b'd\x08\x00\x00'               -a
     49669 b'Q\x05\x00\x00'               -a
     51029 b'\xda\x02\x00\x00'            A1
     51758 b'N\x04\x00\x00'               A2 level
     52859 b'\xaa\x05\x00\x00'            A2P
     54308 b'\xa4\x05\x00\x00'            A3
     55751 b'\xa6\x05\x00\x00'            A4
     57196 b'S\x06\x00\x00'               A5
     58814 b'e\x06\x00\x00'               aa
     60450 b'\x01\x08\x00\x00'            AA
     62498 b'\x8c\x02\x00\x00'            AAA
     63149 b'n\x04\x00\x00'               AAAS
     64282 b'\xd9\x02\x00\x00'            Aachen
     65010 b'.\x08\x00\x00'               AAD
     67103 b'\x90\x03\x00\x00'            Aadhaar
     68014 b'\n\x04\x00\x00'              Aalborg
     69047 b'h\x02\x00\x00'               Aalto, Alvar
     69662 b'\xac\x05\x00\x00'            AAM
     71113 b'\x9a\x04\x00\x00'            A & E
     72290 b'\xaa\x03\x00\x00'            A & M
     73227 b'u\x03\x00\x00'               A & P Show
     74111 b'\xef\x04\x00\x00'            A & R
     75373 b'\xed\x07\x00\x00'            aapa
     77401 b'\x8b\x07\x00\x00'            aardvark
     79331 b'N\x06\x00\x00'               aardwolf
     80944 b'\x7f\x03\x00\x00'            aargh
     81838 b'\xfe\x02\x00\x00'            Aarhus
     82603 b'(\x07\x00\x00'               Aaron
     84434 b'%\x06\x00\x00'               Aaronic
     86006 b'\x83\x05\x00\x00'            Aaron's beard
     87416 b'N\x03\x00\x00'               Aaron's rod
     88261 b'j\x02\x00\x00'               AARP
     88878 b'\xab\x06\x00\x00'            A'asia
     90584 b'x\x02\x00\x00'               aasvoel
     91215 b'f\x04\x00\x00'               AAU
     92340 b'\xd1\x05\x00\x00'            AAUP
     93828 b'\xdc\x02\x00\x00'            Ab
     94559 b'&\x03\x00\x00'               Ab
     95364 b'\xcc\x06\x00\x00'            AB
     97103 b'\xa9\x05\x00\x00'            AB
     98551 b'\x89\x06\x00\x00'            ab-
    100223 b'.\x07\x00\x00'               ABA
    102060 b'\xc3\x0b\x00\x00'            abaca
    105070 b'\x8b\t\x00\x00'              aback
    107512 b'1\x03\x00\x00'               abacus
    108328 b'\xe6\x04\x00\x00'            Abadan
    109581 b'$\t\x00\x00'                 Abaddon
    111920 b'H\t\x00\x00'                 abaft
    114295 b'\t\x04\x00\x00'              abaht
    115327 b'\xd2\x07\x00\x00'            Abakan
    117328 b'\x8d\x1d\x00\x00'            abalone
    124892 b'\x8d\x06\x00\x00'            abandon
    126568 b'\xb4\x04\x00\x00'            abandoned
    127771 b'3\x05\x00\x00'               abandonment
    129101 b'U\t\x00\x00'                 abandonware
    131489 b'\x1c\x04\x00\x00'            abase
    132540 b'\x95\n\x00\x00'              abasement
    135248 b'F\x04\x00\x00'               abash
    136341 b'\x07\r\x00\x00'              abashed
    139675 b'\xb3\t\x00\x00'              abate
    142157 b'[\x07\x00\x00'               abatement
    144039 b'F\x05\x00\x00'               abatis
    145388 b"'\x05\x00\x00"               abattoir
    146706 b'\xab\x04\x00\x00'            a battuta
    147900 b'\xee\x04\x00\x00'            abaxial
    149161 b'4\n\x00\x00'                 abaya
    151772 b'\x96\x03\x00\x00'            Abba
    152689 b'K\x07\x00\x00'               Abba
    154555 b'\xcc\x03\x00\x00'            abbacy
    155526 b'\xdc\x03\x00\x00'            Abbas, Ferhat
    156513 b'\xeb\x06\x00\x00'            Abbas, Mahmoud
    158283 b' \x06\x00\x00'               Abbasid
    159850 b'c\x07\x00\x00'               abbatial
    161740 b'\x92\x03\x00\x00'            abbé
    162653 b'\xbe\x06\x00\x00'            Abbe, Ernst
    164378 b'\x17\x0b\x00\x00'            abbess
    167216 b'\xe9\x07\x00\x00'            Abbevillian
    169240 b'+\x08\x00\x00'               abbey
    171330 b'c\x03\x00\x00'               abbot
    172196 b'\xf1\x08\x00\x00'            Abbott, Tony
    174484 b'|\x04\x00\x00'               abbreviate
    175631 b'\xdb\x08\x00\x00'            abbreviated
    177897 b'\xa2\x0c\x00\x00'            abbreviation
    181130 b'K\x05\x00\x00'               ABC
    182484 b'\x15\x08\x00\x00'            ABC
    184552 b'\x1a\x02\x00\x00'            ABC
    185089 b'\xc4\x03\x00\x00'            ABC Islands
    186052 b'C\x06\x00\x00'               ABD
    187654 b'\xcd\x0e\x00\x00'            abdabs
    191442 b'\x86\t\x00\x00'              abdicate
    193879 b'\xeb\x06\x00\x00'            abdication
    195649 b'[\x08\x00\x00'               abdomen
    197787 b'\x9d\x04\x00\x00'            abdominal
    198967 b'\xba\x03\x00\x00'            abdominoplasty
    199920 b'$\x04\x00\x00'               abdominous
    200979 b'\xaf\x06\x00\x00'            abducens
    202689 b'i\x0b\x00\x00'               abducens nerve
    205609 b'k\x03\x00\x00'               abduct
    206483 b'\x02\x0b\x00\x00'            abductee
    209300 b'-\x0c\x00\x00'               abduction
    212416 b'<\x03\x00\x00'               abductor
    213243 b'u\x03\x00\x00'               Abduh, Muhammad
    214127 b'\xb4\x03\x00\x00'            Abdul Hamid II
    215074 b'\x87\x03\x00\x00'            Abdullah ibn Hussein
    215976 b';\x03\x00\x00'               Abdul Rahman, Tunku
    216802 b'\xa6\t\x00\x00'              Abe, Shinzo
    219271 b'\xdc\t\x00\x00'              abeam
    221794 b'n\x03\x00\x00'               abecedarian
    222671 b'Q\x06\x00\x00'               abed
    224287 b'\xe4\x02\x00\x00'            abeer
    225026 b'\xd2\x03\x00\x00'            Abel
    226003 b'u\x03\x00\x00'               Abel, Niels Henrik
    226887 b'\x98\x06\x00\x00'            Abelard, Peter
    228574 b'w\x05\x00\x00'               abele
    229972 b'V\x07\x00\x00'               abelia
    231849 b'\x1f\x05\x00\x00'            abelian
    233159 b'\x13\x03\x00\x00'            Abenomics
    233945 b'2\x03\x00\x00'               Abeokuta
    234762 b'\x90\x03\x00\x00'            Aberdeen
    235673 b'\x1e\x06\x00\x00'            Aberdeen, 4th Earl of
    237238 b'C\x03\x00\x00'               Aberdeen Angus
    238072 b'O\x07\x00\x00'               Aberdeenshire
    239942 b'0\x03\x00\x00'               Aberdonian
    240757 b'\xac\r\x00\x00'              Aberfan
    244256 b'=\x0e\x00\x00'               aberrant
    247900 b'@\x03\x00\x00'               aberration
    248731 b'\x14\r\x00\x00'              Abertawe
    252078 b'\xdc\x04\x00\x00'            abet
    253321 b'H\x0b\x00\x00'               abettor
    256208 b'\x80\x03\x00\x00'            abeyance
    257103 b'\x8c\x06\x00\x00'            ABH
    258778 b'\xba\t\x00\x00'              abhinaya
    261267 b'3\x05\x00\x00'               abhor
    262597 b'\xdc\x08\x00\x00'            abhorrence
    264864 b'\x8b\x12\x00\x00'            abhorrent
    269610 b'\xc1\x06\x00\x00'            abide
    271338 b'\x15\x03\x00\x00'            abiding
    272126 b'\x92\x05\x00\x00'            Abidjan
    273551 b'\x9e\r\x00\x00'              abigail
    277036 b''                            ability
0.5% // 696 entries parsed // Latest entry: acorn
1.8% // 2252 entries parsed // Latest entry: align
3.1% // 3755 entries parsed // Latest entry: antimony
4.4% // 5227 entries parsed // Latest entry: associated
5.7% // 6694 entries parsed // Latest entry: balance
7.0% // 8161 entries parsed // Latest entry: befuddled
8.3% // 9703 entries parsed // Latest entry: blackhead
9.6% // 11144 entries parsed // Latest entry: Bosch, Hieronymus
10.9% // 12581 entries parsed // Latest entry: Buckingham Palace
12.2% // 14014 entries parsed // Latest entry: Campobasso
13.5% // 15515 entries parsed // Latest entry: celebrate
14.8% // 17070 entries parsed // Latest entry: chocolate-box
16.1% // 18515 entries parsed // Latest entry: coarse
17.4% // 19870 entries parsed // Latest entry: concert grand
18.7% // 21219 entries parsed // Latest entry: corporal punishment
20.0% // 22651 entries parsed // Latest entry: crosspatch
21.3% // 24105 entries parsed // Latest entry: dart
22.6% // 25574 entries parsed // Latest entry: deplume
23.9% // 26982 entries parsed // Latest entry: discalced
25.2% // 28421 entries parsed // Latest entry: douceur de vivre
26.5% // 29883 entries parsed // Latest entry: East Indian
27.8% // 31361 entries parsed // Latest entry: endurance
29.1% // 32815 entries parsed // Latest entry: ex-
30.4% // 34143 entries parsed // Latest entry: fashion-forward
31.7% // 35610 entries parsed // Latest entry: Five Pillars of Islam
33.0% // 37061 entries parsed // Latest entry: forsooth
34.3% // 38558 entries parsed // Latest entry: gaberdine
35.6% // 40153 entries parsed // Latest entry: girlie mag
36.9% // 41713 entries parsed // Latest entry: Great Nebula
38.2% // 43303 entries parsed // Latest entry: hammer
39.5% // 44735 entries parsed // Latest entry: herbal
40.8% // 46252 entries parsed // Latest entry: horde
42.1% // 47881 entries parsed // Latest entry: ill-fitting
43.4% // 49345 entries parsed // Latest entry: initialization
44.7% // 50888 entries parsed // Latest entry: Isoptera
46.0% // 52430 entries parsed // Latest entry: Kango
47.3% // 54055 entries parsed // Latest entry: l
48.6% // 55545 entries parsed // Latest entry: leguminous
49.9% // 56983 entries parsed // Latest entry: loading shovel
51.2% // 58557 entries parsed // Latest entry: madeleine
52.5% // 60083 entries parsed // Latest entry: masochist
53.8% // 61574 entries parsed // Latest entry: metronidazole
55.1% // 63171 entries parsed // Latest entry: moleskins
56.3% // 64774 entries parsed // Latest entry: Murchison Rapids
57.6% // 66313 entries parsed // Latest entry: neuroimaging
58.9% // 68031 entries parsed // Latest entry: Num.
60.2% // 69642 entries parsed // Latest entry: operation
61.5% // 71268 entries parsed // Latest entry: oyster plant
62.8% // 72719 entries parsed // Latest entry: past master
64.1% // 74216 entries parsed // Latest entry: Perth
65.4% // 75772 entries parsed // Latest entry: pixie cut
66.7% // 77175 entries parsed // Latest entry: poppet-head
68.0% // 78672 entries parsed // Latest entry: prime
69.3% // 80044 entries parsed // Latest entry: pultrude
70.6% // 81410 entries parsed // Latest entry: rake
71.9% // 82736 entries parsed // Latest entry: refreshed
73.2% // 84029 entries parsed // Latest entry: revertible
74.5% // 85432 entries parsed // Latest entry: round
75.8% // 86918 entries parsed // Latest entry: sappy
77.1% // 88318 entries parsed // Latest entry: sea robin
78.4% // 89875 entries parsed // Latest entry: shabby
79.7% // 91225 entries parsed // Latest entry: sign
81.0% // 92619 entries parsed // Latest entry: smilax
82.3% // 94147 entries parsed // Latest entry: spatialize
83.6% // 95520 entries parsed // Latest entry: star-spangled
84.9% // 96859 entries parsed // Latest entry: stromatolite
86.2% // 98323 entries parsed // Latest entry: swadeshi
87.5% // 99747 entries parsed // Latest entry: tax bracket
88.8% // 101222 entries parsed // Latest entry: thot
90.2% // 102635 entries parsed // Latest entry: Tosk
91.5% // 104020 entries parsed // Latest entry: troublesome
92.7% // 105623 entries parsed // Latest entry: uncreated
94.1% // 107620 entries parsed // Latest entry: upward
95.3% // 109193 entries parsed // Latest entry: virtu
96.6% // 110663 entries parsed // Latest entry: website
97.9% // 112208 entries parsed // Latest entry: witness
99.2% // 113752 entries parsed // Latest entry: zinnia
Traceback (most recent call last):
  File "/Users/pk49800/Downloads/reverse_data.py", line 406, in <module>
    main()
  File "/Users/pk49800/Downloads/reverse_data.py", line 75, in main
    save_definitions(flags.dictionary_path,
  File "/Users/pk49800/Downloads/reverse_data.py", line 84, in save_definitions
    word_dict = WordDictionary.from_file(dictionary_path)
  File "/Users/pk49800/Downloads/reverse_data.py", line 116, in from_file
    d, links = parse(p)
  File "/Users/pk49800/Downloads/reverse_data.py", line 175, in parse
    entries_tuples = _parse(dictionary_path)
  File "/Users/pk49800/Downloads/reverse_data.py", line 207, in new_func
    res = func(*args, **kwargs)
  File "/Users/pk49800/Downloads/reverse_data.py", line 256, in _parse
    new_entries, stop = _split(res, verbose=first)
  File "/Users/pk49800/Downloads/reverse_data.py", line 311, in _split
    assert (entry_text.startswith('<d:entry') and
AssertionError: ENTRY: <d:entry xmlns:d="http://www.apple.com/DTDs/DictionaryService-1.0.rng" id="fbm_PrefaceToTheFirstEdition" d:title="" class="entry">
 REM: b'<d:entry xmlns:d="http://www.apple.com/DTDs/DictionaryService-1.0.rng" id="fbm_PrefaceToTheFirstEdition" d:title="" class="entry">\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<title></title>\n<link rel="stylesheet" type="text/css" media="screen" href="fbm.css" 
--------------------------------------------------skip long text-------------------------------------------------------------------
>\n</body>\n</html>\n</d:entry>\n'

**Comment by fab-jul** [comment]
It works for me with the `New Oxford American Dictionary.`. It looks like you used another dictionary?

**Comment by fab-jul** [comment]
Updated the readme in 312b5d0, please try with the correct and re-open if it does not work.

**Comment by JBHua** [comment]
I've encounter the same issue. It turns out that some entries do not resemble an actual vocabulary. For example, some entires will have an id of "fbm_PrefaceToTheFirstEdition", "ref_CountriesOfTheWorld", "ref_StandardWeightsAndMeasures". 

These kind of entry will have an empty title and empty content, and it will end with 'class="entry">'. And this is why the assertion failed.

I fixed it simply by adding 
```
if entry_text.endswith('class="entry">'):
    break
```
before the assertion.
